<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<script type="text/javascript" src="Promises.js"></script>
	</head>
	<body>
	</body>
</html>
<script type="text/javascript">
	/**
	 * 2.2.1 onFulfilled和onRejected都是可选的
	 * ** promise.then(onFulfilled, onRejected) 
	 * ** 1.如果onFulfilled不是一个函数，则忽略之
	 
			var Pro = new Promises((resolve, reject)=>{
				setTimeout(()=>{
					resolve('success！')
				},500)
			})
			
		    Pro.then(11,(err)=>{
		        console.log(err)
		    })
		    .then(222,(data)=>{
		        console.log(data)
		    })
		    .then((data)=>{
		    	alert(data) //success!
		    })
		    
	 * ** 2.如果onRejected不是一个函数，则忽略之。
	 
	 		var Pro = new Promises((resolve, reject)=>{
				setTimeout(()=>{
					resolve('success！')
				},500)
			})
			
		    Pro.then(11,22)
		    .then(222,22)
		    .then(33,function(data){
		    	alert(data)  //不执行
		    })
		          或
		    Pro.then(11,22)
		    .then(222,22)
		    .then((data)=>{
		    	alert(data)  //success！
		    })
		    
	 * 2.2.2 如果onFulfilled是一个函数:
	 *  ** 1.它必须在promise fulfilled后调用， 且promise的value为其第一个参数。
	 		
	 		var Pro = new Promises((resolve, reject)=>{
				setTimeout(()=>{
					resolve('success！')
				},500)
			})
			
		    Pro.then((val)=>{
		        console.log(val) //success！
		    })
		    
		** 2.它不能在promise fulfilled前调用。
		   
		    var promise = new Promises((resolve)=>{
			    resolve(1)
			    console.time('fulfill')
			});
			promise.then((value)=>{
			    console.timeEnd('fulfill') //28ms的延迟   不成立则会报错
			})
			
	    ** 3.不能被多次调用。
		    
		    var promise = new Promises((resolve)=>{
			    resolve(1) //执行
			    resolve(2) //不执行
			});
			promise.then((value)=>{
			    console.log(value) //1
			})
			
	 * 2.2.3 如果onRejected是一个函数:
	 *  ** 1.它必须在promise rejected后调用， 且promise的reason为其第一个参数。
	 		
	 		var Pro = new Promises((resolve, reject)=>{
				setTimeout(()=>{
					reject('error！')
				},500)
			})
			
		    Pro.then((val)=>{
		        console.log(val)
		    },(err)=>{
		        console.log(err) //error
		    })
		    
		** 2.它不能在promise rejected前调用。
		   
		    var promise = new Promises((resolve,reject)=>{
			    reject(1)
			    console.time('rejects')
			});
			promise.then((value)=>{
			    console.timeEnd('rejects')
			},(err)=>{
			    console.timeEnd('rejects') //22ms的延迟   不成立则会报错
			})
			
	    ** 3.不能被多次调用。
		    
		    var promise = new Promises((resolve, reject)=>{
			    reject(1) //执行
			    reject(2) //不执行
			});
			promise.then((value)=>{
			    console.log(value)
			},err=>{
				console.log(err) //1
			})
			
	 * 2.2.4 onFulfilled和onRejected是在执行环境中仅包含平台代码时调用
	 * 
	    	理解js的微任务  宏任务 原生的promise是一个微任务  执行优先级高于宏任务
	    	进入整体代码(宏任务)后，开始第一次循环。接着执行所有的微任务。然后再次从宏任务开始，找到其中一个任务队列执行完毕，再执行所有的微任务
	    	
	 * 2.2.5 onFulfilled和onRejected必须作为函数来调用，没有this值
	   
	   		Promises.resolve(1).then(()=>{
		   		console.log(this) //ie为undefined  其他代表window
		    })
		    
	 * 2.2.6 同一个promise上的then方法可能会调用多次
	  
	  	** 1. 当promise fulfilled后，所有onFulfilled都必须按照其注册顺序执行。
	  	** 2. 当promise rejected后，所有OnRejected都必须按照其注册顺序执行。
	  		var i = 0
	  		var Pro = new Promises((resolve, reject)=>{
				setTimeout(()=>{
					resolve('success！')
					i++
				},500)
			})
			
		    Pro.then((val)=>{
		        console.log(i++) //1
		    })
		    Pro.then((val)=>{
		        console.log(i++) //2
		    })
		    Pro.then((val)=>{
		        console.log(i++) //3
		    })
	  		
	 * 2.2.7 then方法会返回一个全新的promise promise2 = promise1.then(onFulfilled, onRejected);
	    ** 1.如果onFulfilled 或 onRejected 返回了值x, 则执行resolve(promise2, x)
	    	
	    	var promise = new Promises((resolve)=>{
			    resolve(1)
			});
			promise.then((value)=>{
			    return value
			}).then(val => {
				console.log(val) //1
			})
	    	
	    ** 2.如果onFulfilled 或 onRejected抛出了异常e, 则promise2应当以e为reason被拒绝
	      
	       var promise = new Promises((resolve)=>{
			    resolve(1)
			});
			promise.then((value)=>{
			    throw new Error('error')
			}).catch(val => {
				console.log(val) //Error: error
			})
	    
	    ** 3.如果 onFulfilled 不是一个函数且promise1已经fulfilled，则promise2必须以promise1的值fulfilled.
	    	
	    	var promise = new Promises((resolve)=>{
			    resolve(1)
			});
			promise.then(11).then(val => {
				console.log(val) //1
			})
	    
	    ** 4.如果 OnReject 不是一个函数且promise1已经rejected, 则promise2必须以相同的reason被拒绝.
	      
	       var promise = new Promises((resolve, reject)=>{
			    reject('err')
			});
			promise.catch(11).catch(val => {
				console.log(val) //1
			})
	    
	 * 2.3 Promise解析过程 是以一个promise和一个值做为参数的抽象过程，可表示为[[Resolve]](promise, x). 
	 	** 1.如果promise 和 x 指向相同的值, 使用 TypeError做为原因将promise拒绝。
	 		
	 		var defer = {}
			var promise = new Promises(function(resolve){ 
			    defer.resolve = resolve
			})
			promise.catch(function(reason){
			    console.log(reason)  //TypeError: resolve 参数不能为实例本身！
			})
			defer.resolve(promise)
			
	    ** 2. 如果val是一个promise对象，且是基于当前实现创建的。
	 		
	 		** 1. 如果val处于pending状态，则promise同样pending并直到val状态改变。
	 		** 2. 如果value处于fulfilled状态，则使用相同的value值fulfill promise。
			** 3. 如果value处于rejected状态，则使用相同的reason值reject promise。
	 			
	 			var promise1 = new Promise((resolve) => {
				    setTimeout(() => {
				        resolve(5)
				    },3000)
				});
				console.time('fulfill')
				var promise = new Promise((resolve) => {
				    resolve(promise1)
				})
				promise.then((value) => {
				    console.timeEnd('fulfill')
				    console.log('fulfill', value)
				})
				setTimeout(()=>{
				    console.log('setTimeout', promise)
				}, 1000)
	 	
	 	** 3. 如果 then 是一个函数， 以x为this调用then函数， 且第一个参数是resolvePromise，第二个参数是rejectPromise，且：
    */
	  	

</script>
